baseURL = "https://www.mdkarthik.com/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Karthik MD"
    author = "karthik md"
    description = "Website title"
    copyright = "Copyright"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false 

    [params.favicons]
        use = true
        metas = '''
               <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
               <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
               <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
               <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
               <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
               <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
               <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
               <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
               <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
               <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
               <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
               <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
               <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
               <link rel="manifest" href="/manifest.json">
               <meta name="msapplication-TileColor" content="#ffffff">
               <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
               <meta name="theme-color" content="#ffffff">
'''
#'''
#        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon_1.png">
#        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32_1.png">
#        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16_1.png">
#        <link rel="manifest" href="site.webmanifest">
#       <link rel="mask-icon" href="safari-pinned-tab_1.svg" color="#252627">
#        <link rel="shortcut icon" href="favicon.ico">
#        '''

    # Profile section
    [params.profile]
        name = "Karthik Mahesh Devaki"
        tagline = "Linux Admin"
        location = "Chennai"
        photo = "profile1.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/karthik-md-4513b3132"
            title = "Linkedin"		
        [[params.social.list]]
           icon = "fab fa-facebook-f"
             url = "https://www.facebook.com/karthik.karthik.731/"
            title = "facebook"
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/mkarthikd"
            title = "github"
        [[params.social.list]]
            icon = "fab fa-instagram"
            url = "https://www.instagram.com/mahesh.karthik/"
            title = "Instagram"
       # [[params.social.list]]
       #     icon = "fab fa-orcid"
       #     url = "#"
       #     title = "Orcid"
       # [[params.social.list]]
       #     icon = "ai ai-google-scholar"
       #     url = "#"
       #     title = "Google Scholar"
       # [[params.social.list]]
       #     icon = "fab fa-researchgate"
       #     url = "#"
       #     title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
   # [[params.showInAccordion]]
   #     item = "publication"
   # [[params.showInAccordion]]
   #     item = "project"
    [[params.showInAccordion]]
        item = "skill"
   # [[params.showInAccordion]]
   #     item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "My name is MD.Karthik, I live in Chennai, India. I am pursuing Linux and Python programming to become a part of the IT industry. I previously worked at Josh Tech Services Pvt Ltd in Bangalore, India, where I used to be a part of Logistics & Inventory using SAP(end-user) software for analyzing overall transactions for Inward & Outward and generating appropriate reports for clients."


    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Logistics Excecutive"
            dates = "2020(FEB) - 2021(FEB)"
            company = "Josh Tech Services Pvt Ltd (Bangalore)"
            details = "Utilized warehousing and distribution infrastructure to optimize transportation routes by combining shipments. Documented physical supply chain processes, including workflows, cycle times and position responsibilities. Coordinated and monitored distribution operations through SAP.By analyzing and negotiating freight costs, reduced transit times, minimized handling, and maximized cost savings. Shipped and received a wide range of products every day."
        [[params.experience.list]]
            position = "Logistics & Inventory"
            dates = "2021(FEB) - 2021(NOV)"
            company = "Josh Tech Services Pvt Ltd (Chennai)"
            URL ="http://www.joshtech.com/"
            details = "Ensured records and documentation are accurate and up-to-date with current information to prevent errors in processing or delivery. Worked with supervisors and team members to understand supply needs and bring levels within desired tolerances.Creating updated status reports in SAP for quick reference on project progress and deadlines. Auditing and rectifying discrepancies in inventory numbers. Unloading shipments, reviewing merchandise and tracking paperwork.Conducted data collection to maintain records current and accurate. Communicated with managers, sales teams, and engineering personnel to revise plans and achieve demanding goals.Responsible for managing complex projects under leadership's direction, delivering positive results within budget and time constraints. Completed physical inventory counts every month. Verified prices and calculated totals for accurate invoice processing.We discovered that warehouse releases were never invoiced, resulting in more than Rs.200K in unbilled charges."

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Bachelor of Computer Science"
            college = "University of Madras(60%)"
            dates = "2014 - 2017"
          #  thesis_title = "Effect of humans on other humans: a study of human behavior."
          #  thesis_url = "#"
       # [[params.education.list]]
       #     degree = "M.S."
       #     college = "University of State-City"
       #     dates = "2013 - 2018"
       #     thesis_title = "Effect of humans on other humans: a study of human behavior."
       #     thesis_url = "#"
       # [[params.education.list]]
       #     degree = "B.S. in Subject"
       #     college = "University of State-City"
       #     dates = "2004 - 2009"

    # Publication section
  #  [params.publication]
  #      title = "Publications"
  #      icon = "fas fa-book"
  #      #The order below determines the order in which the items appear in "Publications" section
  #      format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
  #      types = ["Journal Articles", "Proceedings"]

  #      [[params.publication.list]]
  #          title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  #          authors = "F Last, F Second, P secondary"
  #          date = "2018"
  #          journal = "Journal of Field 52 (16), 9033-9044"
  #          url = "#"
  #          type = "Journal Articles"

  #      [[params.publication.list]]
  #          title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  #          authors = "F Last, F Second, P secondary"
  #          date = "2018"
  #          journal = "Journal of Field 52 (16), 9033-9044"
  #          url = "#"
  #          type = "Journal Articles"
		
  #      [[params.publication.list]]
  #          title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  #          authors = "F Last, F Second, P secondary"
  #          date = "2018"
  #          journal = "Journal of Field 52 (16), 9033-9044"
  #          url = "#"
  #          type = "Proceedings"

  #  # Project section
  #  [params.project]
  #      title = "Projects"
  #      icon = "fas fa-project-diagram"

  #     [[params.project.list]]
  #          title = "Project 1"
  #          url = "#"
  #          description = "Description of the project"
  #      [[params.project.list]]
  #          title = "Project 2"
  #          url = "#"
  #          description = "Description of the project"
  #      [[params.project.list]]
  #          title = "Project 3"
  #          url = "#"
  #          description = "Description of the project"
  #      [[params.project.list]]
  #         title = "Project 4"
  #          url = "#"
  #          description = "Description of the project"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Linux"
            skillrating = 60
        [[params.skill.list]]
            skill = "python"
            skillrating = 50
        [[params.skill.list]]
            skill = "Git"
            skillrating = 40

    # Hobby section
   # [params.hobby]
   #     title = "Hobbies"
   #     icon = "fas fa-gamepad"

    #    [[params.hobby.list]]
    #        hobby = "Cooking"
    #    [[params.hobby.list]]
    #        hobby = "Hiking"
    #    [[params.hobby.list]]
    #        hobby = "Baking"
[menu]
  [[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 4
