name = "Karthik MD"
license = "MIT"
licenselink = "http://mdkarthik.com"
description = "Portfolio and blog theme with multiple theme colors"
homepage = "https://github.com/mkarthikd/"
tags = ["portfolio", "accordion", "resume", "blog"]
features = ["responsive", "dark", "clean"]
min_version = "0.80.0"

[author]
  name = "Karthik MD"
  homepage = "https://www.mdkarthik.com/"
